Repository hassio-addons/addon-jupyterlab, pull requests merged in 2022-09, with the labels that each got.

#323 ⬆️ Upgrades add-on base image to 6.1.2
  jupyterlab/Dockerfile
  jupyterlab/build.yaml
Labels: dependencies

#321 Allow us to run as root
  jupyterlab/rootfs/etc/services.d/jupyter/run
Labels: bugfix

#325 Add pip updates to dependabot
  .github/dependabot.yaml
Labels: ci

#326 Update and rename for jupyter server
  jupyterlab/rootfs/etc/cont-init.d/jupyter.sh
  jupyterlab/rootfs/etc/jupyter/jupyter_notebook_config.gtpl
  jupyterlab/rootfs/etc/jupyter/jupyter_server_config.gtpl
  jupyterlab/rootfs/etc/services.d/jupyter/run
Labels: bugfix
